---
apiVersion: v1
kind: Service
metadata:
  name: ptp-event-publisher-service-{{.NodeName}}
  namespace: openshift-ptp
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ptp-event-publisher-certs-{{.NodeName}}
    prometheus.io/scrape: "false"
  labels:
    app: linuxptp-daemon
spec:
  clusterIP: None
  selector:
    app: linuxptp-daemon
    nodeName: {{.NodeName}}
  ports:
    - name: publisher-port
      port: 9043
  sessionAffinity: None
  type: ClusterIP
