---
apiVersion: v1
kind: Service
metadata:
  name: ptp-event-publisher-service-{{.NodeName}}
  namespace: openshift-ptp
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ptp-event-publisher-certs-{{.NodeName}}
    prometheus.io/scrape: "false"
  labels:
    app: linuxptp-daemon
spec:
  clusterIP: None
  selector:
    app: linuxptp-daemon
    nodeName: {{.NodeName}}
  ports:
    - name: publisher-port
      port: 9043
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ptp-event-publisher-ca-bundle-{{.NodeName}}
  namespace: openshift-ptp
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ptp-event-publisher-auth-{{.NodeName}}
  namespace: openshift-ptp
data:
  config.json: |
    {
      "enableMTLS": true,
      "useServiceCA": true,
      "caCertPath": "/etc/cloud-event-proxy/ca-bundle/service-ca.crt",
      "serverCertPath": "/etc/cloud-event-proxy/server-certs/tls.crt",
      "serverKeyPath": "/etc/cloud-event-proxy/server-certs/tls.key",
      "enableOAuth": true,
      "useOpenShiftOAuth": true,
      "oauthIssuer": "https://oauth-openshift.apps.cnfdg4.sno.ptp.eng.rdu2.dc.redhat.com",
      "oauthJWKSURL": "https://oauth-openshift.apps.cnfdg4.sno.ptp.eng.rdu2.dc.redhat.com/oauth/jwks",
      "requiredScopes": ["user:info"],
      "requiredAudience": "openshift",
      "serviceAccountName": "cloud-event-proxy-sa",
      "serviceAccountToken": "/var/run/secrets/kubernetes.io/serviceaccount/token"
    }
